#!/usr/bin/env bash

####################################################################################
# Copyright (c) 2016 Andriy Kmit'                                                  #
#                                                                                  #
# Permission is hereby granted, free of charge, to any person obtaining a copy of  #
# this software and associated documentation files (the "Software"), to deal in    #
# the Software without restriction, including without limitation the rights to     #
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of #
# the Software, and to permit persons to whom the Software is furnished to do so,  #
# subject to the following conditions:                                             #
#                                                                                  #
# The above copyright notice and this permission notice shall be included in all   #
# copies or substantial portions of the Software.                                  #
#                                                                                  #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR       #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS #
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR   #
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER   #
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN          #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.       #
####################################################################################

#################################################################################
# Helper for archiving subset of files of a home directory for a list of users. #
# List of files to be archived is specified per-user.                           #
#################################################################################

set -eu

################################################################################
#
# Variables
#

archive_fname_format='home-%s.tgz'
# User names
users=(root madand)
# Each user has separate variable with list of files to archive.
# Variable name must be files_list_{username}.
files_list_root='.vim* bin/ etc/ scripts/'
files_list_madand='.ssh .bashrc'

################################################################################
#
# Requirements checks and init
#

[ $UID -ne 0 ] && { echo 'Please run me as root!'; exit 1; }

if [ $# -lt 1 ]; then
    echo "USAGE: $(basename $0) archive [archives-dir]"
    echo "       $(basename $0) extract root-dir [archives-dir]"
    exit 1
fi

case $1 in
    archive)
        work_fun=archive_user_files ;;
    extract)
        work_fun=extract_user_files
        root_dir=$2
        shift
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
esac

archives_dir=${2:-$(pwd)}

# Output all further commands
set -x

################################################################################
#
# Main function
#

main() {
    mkdir -p $archives_dir

    for user_name in ${users[@]}; do
        eval $work_fun $user_name
    done
}

################################################################################
#
# Functions
#

# USAGE: get_archive_path USER-NAME
# Get absolute path of the archive file of the given user.
get_archive_path() {
    printf $archives_dir/$(printf "$archive_fname_format" $1)
}

# USAGE: archive_user_files USER-NAME
# Archive files of the given user.
archive_user_files() {
    [ $# -ne 1 ] && { echo 'USAGE: archive_user_files USER-NAME'; exit 1; }

    local archive_path=$(get_archive_path $1)

    eval cd ~$1
    eval tar caf $archive_path \${files_list_$1}
}

# USAGE: extract_user_files USER-NAME
# Archive files of the given user.
extract_user_files() {
    [ $# -ne 1 ] && { echo 'USAGE: extract_user_files USER-NAME'; exit 1; }

    local archive_path=$(get_archive_path $1)

    if [ $1 = "root" ]; then
        eval cd $root_dir/root
    else
        eval cd $root_dir/home/$1
    fi

    eval tar xf $archive_path
}

################################################################################
#
# Run the whole thing
#

main "$@"
