#!/usr/bin/env bash

####################################################################################
# Copyright (c) 2016 Andriy Kmit'                                                  #
#                                                                                  #
# Permission is hereby granted, free of charge, to any person obtaining a copy of  #
# this software and associated documentation files (the "Software"), to deal in    #
# the Software without restriction, including without limitation the rights to     #
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of #
# the Software, and to permit persons to whom the Software is furnished to do so,  #
# subject to the following conditions:                                             #
#                                                                                  #
# The above copyright notice and this permission notice shall be included in all   #
# copies or substantial portions of the Software.                                  #
#                                                                                  #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR       #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS #
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR   #
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER   #
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN          #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.       #
####################################################################################

###############################################################
# Helper for updating IDv2 tags of all files it a directory.  #
# Useful in cases when file names contain track No and Title. #
###############################################################

# Script uses https://github.com/Martchus/tageditor

################################################################################
#
# Variables
#

genre="Soundtrack"
artist="LEXX"
album="Tales From A Parallel Universe"
# Length of possible prefix garbage before track No in file names.
prefix_lenght=6
suffix=".mp3"

################################################################################
#
# Code
#

track_count=$(ls -l *$suffix | wc -l)

for f_orig in *$suffix; do
    name_no_suffix=$(basename "$f_orig" $suffix)
    track_no=${f_orig:$prefix_lenght:2}
    track_title_dirty=${name_no_suffix:$(($prefix_lenght+3))}
    title=${track_title_dirty//_/ }
    echo $track_no
    # tageditor -set --remove-other-fields -f "$f_orig"
    tageditor -set artist="$artist" album="$album" title="$title" \
                   genre="$genre" track="$track_no/$track_count" \
              -f "$f_orig"
done
