#!/usr/bin/env bash

####################################################################################
# copyright (c) 2016 andriy kmit'                                                  #
#                                                                                  #
# permission is hereby granted, free of charge, to any person obtaining a copy of  #
# this software and associated documentation files (the "software"), to deal in    #
# the software without restriction, including without limitation the rights to     #
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of #
# the software, and to permit persons to whom the software is furnished to do so,  #
# subject to the following conditions:                                             #
#                                                                                  #
# the above copyright notice and this permission notice shall be included in all   #
# copies or substantial portions of the software.                                  #
#                                                                                  #
# the software is provided "as is", without warranty of any kind, express or       #
# implied, including but not limited to the warranties of merchantability, fitness #
# for a particular purpose and noninfringement. in no event shall the authors or   #
# copyright holders be liable for any claim, damages or other liability, whether   #
# in an action of contract, tort or otherwise, arising from, out of or in          #
# connection with the software or the use or other dealings in the software.       #
####################################################################################

############################################################################
# Helper script to start/stop Nginx, MySQL, PHP etc with a single command. #
############################################################################

################################################################################
#
# Variables
#

# List of services to be started/stopped by the script.
services_list=(mysqld nginx php-fpm)

################################################################################
#
# Requirements checks and init
#

USAGE="USAGE: $(basename $0) start|stop"

[ $# -eq 0 ] && { echo $USAGE; exit 1; }

################################################################################
#
# Functions
#

services() {
    # Ensure we have sudo password cached, to not destroy our pretty messages.
    until sudo true; do : ; done

    for service in ${services_list[@]}; do
        eval service_$1 $service
    done
}

service_start() {
    local service=$1
    if [ $(service_running $service) -eq 0 ]; then
        echo "$service is already running!"
    else
        printf 'Starting %s... ' $service
        sudo systemctl start $service && echo 'Done!' || echo 'Error!'
    fi
}

service_stop() {
    local service=$1
    if [ $(service_running $service) -ne 0 ]; then
        echo "$service is already stopped!"
    else
        printf 'Stopping %s... ' $service
        sudo systemctl stop $service && echo 'Done!' || echo 'Error!'
    fi
}

service_running() {
    printf $(systemctl --quiet is-active $1; echo $?)
}

################################################################################
#
# Main code
#

case $1 in
    start)
        services start ;;
    stop)
        services stop ;;
    *)
        echo $USAGE; exit 2
esac
