#!/usr/bin/env bash
set -eu

################################################################################
#
# Requirements checks and init
#

[ $UID -ne 0 ] && { echo 'Please run me as root!'; exit 1; }
[ $#   -lt 1 ] && { echo "USAGE: $(dirname $0) ssh-host"; exit 1; }

ssh_host=$1

# Output all further commands
set -x

################################################################################
#
# Main code
#

portsnap fetch update
eval "tar cvzf - /usr/ports /var/db/portsnap | ssh $ssh_host 'cd /mnt; tar xzf -'"
